version: "3.7"
services:
  postgresql:
    image: postgres:9.5
    volumes:
      - "./docker/db/:/docker-entrypoint-initdb.d"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgresql
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  client:
    container_name: client

    build:
      context: .
      dockerfile: "client/Dockerfile"
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - HTTPS=true

  server:
    container_name: server

    build:
      context: .
      dockerfile: "server/Dockerfile"
    volumes:
      - "./server:/app"
      - "/app/node_modules"
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=development
